version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: job-collector-bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - RUN_MODE=webhook
    volumes:
      - ./config.json:/app/config.json
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - bot-network

  job-scheduler:
    build: .
    container_name: job-scheduler
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - RUN_MODE=scheduled
    volumes:
      - ./config.json:/app/config.json
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - bot-network
    command: >
      sh -c "
        echo '0 8,20 * * * cd /app && python src/bot.py' > /etc/crontabs/root &&
        crond -f -d 8
      "

networks:
  bot-network:
    driver: bridge
