services:
  telegram-bot:
    build: .
    container_name: job-collector-bot
    env_file:
      - data/config/bot-secrets.env
    environment:
      - DATABASE_PATH=/app/data/bot.db
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - bot-network
    healthcheck:
      test: ["CMD", "python", "/app/src/health_check.py"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  bot-network:
    driver: bridge
