version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: job-collector-bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - ./config.json:/app/config.json
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
